name: Build and Test
on: [push]

env:
  MATHWORKS_ACCOUNT: ${{ secrets.MATHWORKS_ACCOUNT }}
  MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

jobs:
  bat:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Perform npm tasks
        run: npm run ci
      - uses: actions/upload-artifact@v3
        with:
          name: built-action
          path: |
            **/*
            !node_modules/

  integ:
    needs: bat
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            release: latest 
            products: Simulink
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: built-action
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget unzip ca-certificates
      - run: wget https://mpmtest.s3.amazonaws.com/2023_04_27_11_22_46.zip
      - run: unzip 2023_04_27_11_22_46.zip
      - name: Install selected products
        id: setup_matlab
        uses: ./
        with:
          release: "./2023_04_27_11_22_46"
          products: ${{ matrix.products }}
  
