name: Build and Test
on: [push]

jobs:
  bat:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Perform npm tasks
        run: echo "hello"
  integ:
    needs: bat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Cache files for installer
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: 2023_06_01_09_45_50
          key: cache-matlab
      - name: Get files for installer
        if: steps.cache-matlab.outputs.cache-hit != 'true'
        run: |
          wget -q https://mpmtest.s3.amazonaws.com/2023_06_01_09_45_50.zip -o 2023_06_01_09_45_50.zip
          cat 2023_06_01_09_45_50.zip* > 2023_06_01_09_45_50.zip
      - name: Unzip files
        if: steps.cache-matlab.outputs.cache-hit != 'true'
        run: unzip -q 2023_06_01_09_45_50.zip
      - name: Setup mpm
        run: |
          wget -q mathworks.com/mpm/glnxa64/mpm -o mpm
          chmod +x mpm
      - name: Install MATLAB
        run: |
          ./mpm install --source "$(pwd)/2023_06_01_09_45_50" --destination "$(pwd)" --products MATLAB Parallel_Computing_Toolbox
      - name: Look see
        run: |
          ls
          ls 2023_06_01_09_45_50
