name: Build and Test
on: [push]

jobs:
  bat:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Perform npm tasks
        run: echo "hello"
  integ:
    needs: bat
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      - name: Cache files for installer
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: |
            2023_06_06_09_11_28
            mpm
          key: cache-matlab-win
      - name: Setup deps
        shell: bash
        run: |
          curl -O https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh
          ./install.sh
          # wget -qO- --retry-connrefused https://ssd.mathworks.com/supportfiles/ci/matlab-deps/v0/install.sh | sudo bash -s
      - name: Get files for installer
        if: steps.cache-matlab.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -O https://mpmtest.s3.amazonaws.com/2023_06_06_09_11_28.zip
      - name: Unzip files
        if: steps.cache-matlab.outputs.cache-hit != 'true'
        run: |
          Expand-Archive 2023_06_06_09_11_28.zip -DestinationPath .
      - name: Setup mpm
        if: steps.cache-matlab.outputs.cache-hit != 'true'
        run: |
          curl https://mathworks.com/mpm/win64/mpm -L -o mpm.zip
          Expand-Archive mpm.zip -DestinationPath mpm
          ls mpm/bin/win64
      - name: Install MATLAB
        run: |
          mkdir matlab
          ls .\2023_06_06_09_11_28
          .\mpm\bin\win64\mpm.exe install --source .\2023_06_06_09_11_28 --destination matlab --products MATLAB Parallel_Computing_Toolbox
          Add-Content $env:GITHUB_PATH .\matlab\bin
      - name: Run Sample MATLAB Command
        uses: matlab-actions/run-command@v1
        with:
          command: assert(~isempty(regexp(version('-release'), '\d{4}.')))
