name: Build and Test
on: [push]

jobs:
  integ:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          #- os: windows-latest
          - os: windows-2019
    steps:
    - name: Download WPT
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2026036" -OutFile "C:\adksetup.exe"
    
    - name: Install WPT
      run: |
        C:\adksetup.exe /q /norestart /features OptionId.WindowsPerformanceToolkit
    
    - name: Start ETW Session
      run: |
        xperf -on DiagEasy
    
        
    - name: Perform 'setup-matlab'
      uses: matlab-actions/setup-matlab@v2-beta
    
    - name: Stop ETW Session
      run: |
        xperf -d C:\perf.etl
    
    - uses: actions/upload-artifact@v3
      with:
        name: ETW
        path: C:\perf.etl
